targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generates for the library 'lib/core/di/injection_container.dart'
