name: health_tracker_reports
description: A privacy-first Flutter application for tracking blood test reports with automated OCR extraction, trend analysis, and professional report generation.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Routing
  go_router: ^16.2.4

  # File Handling & Image Processing
  file_picker: ^8.1.6
  pdfx: ^2.7.0
  image: ^4.3.0

  # Charts & PDF Generation
  fl_chart: ^1.1.1
  pdf: ^3.11.1
  printing: ^5.14.1

  # Utilities
  intl: ^0.20.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  uuid: ^4.5.1

  # HTTP & Security
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2

  # Google Drive Integration
  googleapis: ^15.0.0
  google_sign_in: ^7.2.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0

  # Notifications
  flutter_local_notifications: ^19.4.2

  # Sharing
  share_plus: ^12.0.0

  # Icons
  cupertino_icons: ^1.0.8
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2

  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0

  # Linting
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
